apiVersion: v1
kind: Service
metadata:
  name: {{ include "dummy-consumer.fullname" . }}
  labels:
    {{- include "dummy-consumer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "dummy-consumer.selectorLabels" . | nindent 4 }}
